services:

  kamailio:
    image: ghcr.io/kamailio/kamailio:5.8.4-bookworm
    ports:
      - "5070:5060/udp"
      - "5071:5061/tcp"
    depends_on:
      - postgres
    networks:
      - voip_net

  asterisk:
    image: andrius/asterisk:latest
    ports:
      - "5060:5060/udp"
      - "10000-10100:10000-10100/udp"
      - "15060:15060/udp"
    volumes:
      - ./config/asterisk/pjsip.conf:/etc/asterisk/pjsip.conf
    networks:
      - voip_net



  postgres:

    image: postgres:latest
    environment:
      POSTGRES_USER: kamailio
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kamailiodb
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - voip_net

  backend:

    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    volumes:
      - ./backend:/app
    networks:
      - voip_net

  https-proxy:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - voip_net

networks:
  voip_net:
    driver: bridge
