services:

  kamailio:
    image: ghcr.io/kamailio/kamailio:5.8.4-bookworm
    ports:
      - "5070:5060/udp"
      - "5071:5061/tcp"
    depends_on:
      - postgres
    container_name: voip-kamailio
    networks:
      voip_net:
        ipv4_address: 172.28.0.9

  asterisk:
    image: andrius/asterisk:latest
    ports:
      - "5060:5060/udp"
      - "10000-10100:10000-10100/udp"
      - "15060:15060/udp"
    volumes:
      - ./config/asterisk/pjsip.conf:/etc/asterisk/pjsip.conf
    container_name: voip-asterisk
    networks:
      voip_net:
        ipv4_address: 172.28.0.10

  postgres:

    image: postgres:latest
    environment:
      POSTGRES_USER: kamailio
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kamailiodb
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    container_name: voip-postgres
    networks:
      voip_net:
        ipv4_address: 172.28.0.11

  backend:

    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    volumes:
      - ./backend:/app
    container_name: voip-backend
    networks:
      voip_net:
        ipv4_address: 172.28.0.12

  https-proxy:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    container_name: voip-nginx
    depends_on:
      - backend
    networks:
      voip_net:
        ipv4_address: 172.28.0.13

networks:
  voip_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

